"""maps_created_by.

Revision ID: 694335a7a3f9
Revises: a549da799d64
Create Date: 2021-10-21 16:00:49.449412

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "694335a7a3f9"
down_revision = "a549da799d64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maps", sa.Column("created_by", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_foreign_key(None, "maps", "users", ["created_by"], ["id"])
    op.alter_column(
        "roles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint("maps_created_by_fkey", "maps", type_="foreignkey")
    op.drop_column("maps", "created_by")
    # ### end Alembic commands ###
