"""Add maps.

Revision ID: b5ef0a65a83f
Revises: 0acce38ffd69
Create Date: 2021-06-12 01:49:54.895382

"""
import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from server import db

# revision identifiers, used by Alembic.
from server.utils.date_utils import nowtz

revision = "b5ef0a65a83f"
down_revision = "0acce38ffd69"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maps",
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=510), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("size_x", sa.Integer(), nullable=True),
        sa.Column("size_y", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", db.UtcTimestamp(timezone=True), default=nowtz, nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("maps")
    # ### end Alembic commands ###
